version: "3"
networks:
  net: {ipam: {config: [{subnet: 10.0.0.0/24}]}}
services:
  node:
    networks: [net]
    build: .
    image: elixir:local
    environment:
      - MIX_CMD=run
    command: sh ./entrypoint.sh
    volumes:
      - ./entrypoint.sh:/app/entrypoint.sh
      - ./config:/app/config
      - ./deps:/app/deps
      - ./lib:/app/lib
      - ./test:/app/test
      - ./mix.exs:/app/mix.exs
      - ./mix.lock:/app/mix.lock
